# Generated by Django 5.0 on 2023-12-18 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='osoba',
            name='data_dodania',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data dodania'),
        ),
    ]
